name: Tests

on: [ push, pull_request ]

permissions: read-all

jobs:
    laravel:
        runs-on: ubuntu-latest
        
        strategy:
            fail-fast: true
            matrix:
                php: [ "8.2", "8.3", "8.4" ]
                laravel: [ "10.0", "11.0", "12.0" ]
                publisher: [ "15.0", "16.0" ]
                exclude:
                    - laravel: 11.0
                      publisher: 15.0

                    - laravel: 12.0
                      publisher: 15.0
        
        name: PHP ${{ matrix.php }}, L ${{ matrix.laravel }}, P ${{ matrix.publisher }}
        
        steps:
            -   name: Checkout code
                uses: actions/checkout@v5

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: curl, mbstring, zip, pcntl, pdo, pdo_sqlite, iconv, json
                    coverage: xdebug
                env:
                    COMPOSER_TOKEN: ${{ secrets.COMPOSER_TOKEN }}

            -   name: Install dependencies
                run: composer require laravel/framework:^${{ matrix.laravel }} laravel-lang/publisher:^${{ matrix.publisher }}

            -   name: Execute tests
                run: sudo vendor/bin/phpunit --colors=always
